### ISSUE TITLE
数据问题

### ISSUE THREAD

**Issue by zcdliuwei** [wswdx/C2F-FWN#10]
你好，非常感谢您的分享。
我下载了您的数据集，但是里面是26个单独的文件，你的readme文件里面说，把他们放在train和test文件夹下，请问这26个文件，哪些是训练集，哪些是测试集？
另外，预训练模型可以提供一下吗
非常期待您的回复

**Comment by AltoriaDD** [comment]
你好，你得到了预训练模型了吗？可以给我提供一份吗。我现在想做一个效果对比，但是训练该模型于我而言负担太大了 @zcdliuwei

**Comment by zcdliuwei** [comment]
你好，我也没有预训练模型
