### ISSUE TITLE
pretrained weights and colab

### ISSUE THREAD

**Issue by ghost** [wswdx/C2F-FWN#2]
Hi will the pretrained weights be released and can you please make a google colab for inference thanks

**Comment by wswdx** [comment]
Yes, we may release our pretrained weights in the next update. However, we currently have no plan nor enough time to set up a google colab in the near future. You can just follow our guidelines firstly to have a try.

**Comment by melih-unsal** [comment]
Hi, when are you going to release the pre-trained weights? I am looking forward to try this excellent model.
Thanks.

**Comment by wswdx** [comment]
> Hi, when are you going to release the pre-trained weights? I am looking forward to try this excellent model.
> Thanks.

Hi. We'll release the pretrained weights in the near future. Before that, you can follow our guidelines to train your own models.
