### ISSUE TITLE
iPER datasets

### ISSUE THREAD

**Issue by FrankMelon1** [wswdx/C2F-FWN#4]
Thanks for your great work!

Could you share the keypoints and the paring results of the iPER datasets?

I am looking forward to your reply, thanks!

**Comment by wswdx** [comment]
Hi. We might provide these data for iPER datasets recently. Before that, I think you can just follow openpose(https://github.com/CMU-Perceptual-Computing-Lab/openpose) and CIHP(https://github.com/Engineering-Course/CIHP_PGN) to obtain keypoints and parsing results, respectively. Both of them have detailed instructions that are easy to follow.
